### ISSUE TITLE
Lack of Travis

### ISSUE THREAD

**Issue by szajcz** [BME-MIT-IET/Burom-iet-2018#1]
We need Travis CI in our project.

**Comment by pekkr** [comment]
I just added Travis to the project.

**Comment by pekkr** [comment]
The first compile failed.
![image](https://user-images.githubusercontent.com/32883457/39595052-ac7aa2a8-4f0e-11e8-9f80-8e5cae7ce61b.png)

**Comment by pekkr** [comment]
I finnaly made it! I just deleted everything and redid all the work.
![image](https://user-images.githubusercontent.com/32883457/39597417-972ff5f4-4f15-11e8-971a-4563b4ebeefe.png)

**Comment by szajcz** [comment]
Thank you my friend!

**Comment by dubstepz321** [comment]
Approved by me.
