### ISSUE TITLE
SonarQube analysis

### ISSUE THREAD

**Issue by dubstepz321** [BME-MIT-IET/Burom-iet-2018#2]

**Comment by szajcz** [comment]
![31898251_1635695069817386_5143869673703473152_n](https://user-images.githubusercontent.com/34402062/39601091-2767c16e-4f21-11e8-85c1-60340d0b7ee1.png)
I implemented SonarQube successfully, this was the result after the first compile.

**Comment by pekkr** [comment]
I see too, on the Issues page I can see the actual smells and bugs.
![image](https://user-images.githubusercontent.com/32883457/39601291-bef37c08-4f21-11e8-8951-e68afcf717b4.png)

**Comment by dubstepz321** [comment]
Removed unused import.

Commit code: 055a49b8d903090cef63dc33451f817c26874e7a

**Comment by LeBuromJames** [comment]
isIgnored returned 2 times. Fixed it.
Commit code: 4197ef47623440fbde8e99dd2b602b5dd9943055

**Comment by szajcz** [comment]
Fixed a few smells in RDFMapper.
Commit code: a9e267f2447500052f8dc99157fe4df95e6c6681

**Comment by pekkr** [comment]
Great work! We have already reduced the number of smells.
![image](https://user-images.githubusercontent.com/32883457/39603140-a0931a60-4f27-11e8-9be0-87d7f5d510d0.png)

**Comment by LeBuromJames** [comment]
Also fixed "constant name didn't match regular expression" problem.
commit code: 7305dc5f52e26075457c165e2cdddf7ee906695c
