### ISSUE TITLE
JUnit-Tests

### ISSUE THREAD

**Issue by dubstepz321** [BME-MIT-IET/Burom-iet-2018#5]
Writing JUnit tests

**Comment by szajcz** [comment]
I found this untested line:
![image](https://user-images.githubusercontent.com/34402062/40278121-8874f08c-5c2b-11e8-8dec-129f803aac69.png)
I solved the problem with the commit 84015a7359d735ce4ff2f7eee591445d169cabd8

**Comment by szajcz** [comment]
I also tested the Classes class' private constructor, the result:
![image](https://user-images.githubusercontent.com/34402062/40278334-939c0b54-5c2f-11e8-9080-8ee1222c98ed.png)
The commit: 3445adc1003de00ff157e8ada830a758e5f3feb8

**Comment by LeBuromJames** [comment]
Tested private constructor in Fields class:
![image](https://user-images.githubusercontent.com/24385360/40278336-deac0afe-5c2f-11e8-9eaf-4c51331de83f.png)
![image](https://user-images.githubusercontent.com/24385360/40278423-12345dbc-5c31-11e8-8576-8c702850ca3f.png)
![image](https://user-images.githubusercontent.com/24385360/40278425-20e0adfc-5c31-11e8-805f-99fdb215d499.png)
Code coverage improved much.
Commit code: 11424ced7bf417ba611b0847289093ffe443e4e2

**Comment by szajcz** [comment]
Testing isInstantiable method in Classes:
![image](https://user-images.githubusercontent.com/34402062/40278455-98744e46-5c31-11e8-9afd-d459fe7821cb.png)
commit: 185e4208e7fce55b7403dbb6a2c1b309f6bcd285
Now the Classes class is 100% covered.
![image](https://user-images.githubusercontent.com/34402062/40278502-3a50271c-5c32-11e8-9488-2fdd1e72218b.png)

**Comment by dubstepz321** [comment]
Tested private constructor in Methods and Beans class:
![image](https://user-images.githubusercontent.com/36195977/40278544-f2c955d4-5c32-11e8-8b29-dcd616291bc6.png)

![image](https://user-images.githubusercontent.com/36195977/40278539-e158afac-5c32-11e8-9ae1-b79f13e8aa9c.png)

**Comment by LeBuromJames** [comment]
Tested MappinOptions private constructor
![image](https://user-images.githubusercontent.com/24385360/40278564-9b5fb58a-5c33-11e8-957d-123fb2f7df35.png)

Succesfully covered MappingOptions Class:
-before
![image](https://user-images.githubusercontent.com/24385360/40278561-75cf163a-5c33-11e8-9c61-9ae59ca6c3fd.png)
after-
![image](https://user-images.githubusercontent.com/24385360/40278555-508d41bc-5c33-11e8-83d7-7f1defe1b587.png)

Commit code: 00fc08b45227fc62a39bb29fa65d95bc0913e363

**Comment by pekkr** [comment]
This branch is merged to master.
Commit code: 1f5bc0665aa758673e66b15bf9f142b1bb964df9
